name: app_template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  dio: 5.0.0
  flutter_riverpod: 2.1.3
  shared_preferences: 2.0.17
  devicelocale: 0.5.5
  carrier_info: 2.0.8
  connectivity_plus: 3.0.3
  flutter_screenutil: 5.6.1
  flutter_easyloading: 3.0.5
  go_router: 6.0.6
  firebase_core: 2.5.0
  firebase_analytics: 10.1.1
  firebase_crashlytics: 3.0.12
  url_launcher: 6.1.9
  in_app_review: 2.0.6
  device_info_plus: 8.1.0
  uni_links: 0.5.1
  heic_to_jpg: 0.2.0
  flutter_image_compress: 1.1.3
  extended_image: 6.4.1
  path_provider: 2.0.12
  path: 1.8.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test: 
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_intl:
  enabled: true